<a href="https://colab.research.google.com/github/seccily/ColabTricks/blob/main/Patika/hafta3_PythonNumpy/HackerrankNumpyQ%26A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NOTE:** This notebook contains answers of Numpy questions on [Hackerrank](https://www.hackerrank.com/) website.

# 1. [Arrays](https://www.hackerrank.com/challenges/np-arrays/problem)

The NumPy (Numeric Python) package helps us manipulate large arrays and matrices of numeric data.

To use the NumPy module, we need to import it using:
```python
import numpy
```
> **Arrays**

A NumPy array is a grid of values. They are similar to lists, except that every element of an array must be the same type.
```python
import numpy

a = numpy.array([1,2,3,4,5])
print a[1]          #2

b = numpy.array([1,2,3,4,5],float)
print b[1]          #2.0
```
In the above example, numpy.array() is used to convert a list into a NumPy array. The second argument (float) can be used to set the type of array elements.
---
> **Task**

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

* Input Format: ` A single line of input containing space separated numbers.`

* Output Format: `Print the reverse NumPy array with type float.`

* Sample Input:  `1 2 3 4 -8 -10`

* Sample Output ` [-10.  -8.   4.   3.   2.   1.]`

Answer:
---

Importing numpy:

In [ ]:
import numpy

Defining a function which reverses the input array:

In [2]:
# this function returns the input array in reversed and float format 
# arr[::-1] --> this reverses the array
# dtype = "float" --> this returns the array as float data type

def arrays(arr):
    return numpy.array(arr[::-1], dtype = "float") 

In [1]:
arr = input().strip().split(' ') # taking input array from user and splitting it with space character

result = arrays(arr) # passing the input array to arrays() function for reversing process

print(result) # printing the result

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# 2. [Concatenate](https://www.hackerrank.com/challenges/np-concatenate/problem)


Two or more arrays can be concatenated together using the concatenate function with a tuple of the arrays to be joined:
```python
import numpy

array_1 = numpy.array([1,2,3])
array_2 = numpy.array([4,5,6])
array_3 = numpy.array([7,8,9])

print numpy.concatenate((array_1, array_2, array_3))    
```
**Output:** 
`[1 2 3 4 5 6 7 8 9] `

If an array has more than one dimension, it is possible to specify the axis along which multiple arrays are concatenated. By default, it is along the first dimension.
```python
import numpy

array_1 = numpy.array([[1,2,3],[0,0,0]])
array_2 = numpy.array([[0,0,0],[7,8,9]])

print numpy.concatenate((array_1, array_2), axis = 1)   
```
**Output**:
```
[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]     
``` 
---
> **Task**

You are given two integer arrays of size N X P and M X P ( &  are rows, and P is the column). Your task is to concatenate the arrays along axis 0.

* **Input Format:**
```
The first line contains space separated integers N, M  and P.
The next N lines contains the space separated elements of the  columns.
After that, the next M lines contains the space separated elements of the  columns.
``` 
* **Output Format:**

  ```Print the concatenated array of size (N+M) X P.```

* **Sample Input:**
```
4 3 2
1 2
1 2 
1 2
1 2
3 4
3 4
3 4 
```

* **Sample Output:**
```
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 
 ```

Answer:
---

In [5]:
# importing numpy:
import numpy as np

In [4]:
# taking 3 integer inputs from user for defining the shapes of arrays and splitting it:
n, m, p = map(int, input().split()) 

# defining 2 empty lists for creating arrays:
arr1_list = []
arr2_list = []

# appending first n integers into arr1_list for array1:
for _ in range(n):
    arr1_list.append(list(map(int, input().split())))
    
# after first n integers appending m integers into arr2_list for array2:
for _ in range(m):
    arr2_list.append(list(map(int, input().split())))
    
# first concatenating array1 and array2 lists along axis 0 then printing the result:
print(np.concatenate((arr1_list, arr2_list), axis = 0))


4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# 3. [Min and Max](https://www.hackerrank.com/challenges/np-min-and-max/problem) 

## **min**

The tool min returns the minimum value along a given axis.
```python
import numpy

my_array = numpy.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])

print numpy.min(my_array, axis = 0)         #Output : [1 0]
print numpy.min(my_array, axis = 1)         #Output : [2 3 1 0]
print numpy.min(my_array, axis = None)      #Output : 0
print numpy.min(my_array)                   #Output : 0
```

By default, the axis value is None. Therefore, it finds the minimum over all the dimensions of the input array.

## **max**

The tool max returns the maximum value along a given axis.
```python
import numpy

my_array = numpy.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])

print numpy.max(my_array, axis = 0)         #Output : [4 7]
print numpy.max(my_array, axis = 1)         #Output : [5 7 3 4]
print numpy.max(my_array, axis = None)      #Output : 7
print numpy.max(my_array)                   #Output : 7
```
By default, the axis value is None. Therefore, it finds the maximum over all the dimensions of the input array.

---
> **Task**

You are given a 2-D array with dimensions N X M.
Your task is to perform the min function over axis 1 and then find the max of that.

* **Input Format:**
```
The first line of input contains the space separated values of N and M.
The next N lines contains M space separated integers.
```
* **Output Format:**
```
Compute the min along axis 1 and then print the max of that result.
```
* **Sample Input:**
```
4 2
2 5
3 7
1 3
4 0
```
* **Sample Output:**
```
3
```
* **Explanation:**
```
The min along axis 1 = [2, 3, 1, 0] 
The max of [2, 3, 1, 0] = 3 
```

Answer:
---

In [ ]:
# importing numpy:
import numpy as np

In [6]:
# defining an empty list for creating array:
arr_list = []

# taking 2 integer inputs from user for defining the shapes of array and splitting it:
n, m = map(int, input().split())

# appending first n integers into arr1_list for array:
for _ in range(n):
    arr_list.append(list(map(int, input().split())))

# creating an array from `arr_list` list
arr = np.array(arr_list)

# computing the min of the array along axis 1 and then print the max of that result.
print(np.max(np.min(arr, axis = 1)))

4 2
2 5
3 7
1 3
4 0
3


# 4. [Sum and Prod](https://www.hackerrank.com/challenges/np-sum-and-prod/problem) 

## **sum**

The sum tool returns the sum of array elements over a given axis.
```python
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.sum(my_array, axis = 0)         #Output : [4 6]
print numpy.sum(my_array, axis = 1)         #Output : [3 7]
print numpy.sum(my_array, axis = None)      #Output : 10
print numpy.sum(my_array)                   #Output : 10
```
By default, the axis value is None. Therefore, it performs a sum over all the dimensions of the input array.

## **prod**

The prod tool returns the product of array elements over a given axis.
```python
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.prod(my_array, axis = 0)            #Output : [3 8]
print numpy.prod(my_array, axis = 1)            #Output : [ 2 12]
print numpy.prod(my_array, axis = None)         #Output : 24
print numpy.prod(my_array)                      #Output : 24
```
By default, the axis value is None. Therefore, it performs the product over all the dimensions of the input array.

---

> **Task**

You are given a 2-D array with dimensions N X M.
Your task is to perform the sum tool over axis 0 and then find the product of that result.

* **Input Format:**
```
The first line of input contains space separated values of N and M.
The next N lines contains M space separated integers.
```
* **Output Format:**
```
Compute the sum along axis 0. Then, print the product of that sum.
```
* **Sample Input:**
```
2 2
1 2
3 4
```
* **Sample Output:**
```
24
```
* **Explanation:**
```
The sum along axis 0 = [4 6]
The product of this sum = 24
```

Answer
---

In [8]:
# importing numpy:
import numpy as np

In [9]:
# I am not going to use second input so after taking the inputs and splitting them
# I only defined the first integer input as n 
n, _ = map(int, input().split())

# here used list comprehension for loops
# at first taking first n integer inputs and splitting them for creating list
# then applying map() function for defining the input values as integer data type
# then using list() function for creating a list from defined map object
# lastly creating an array from defined list
arr = np.array([list(map(int, input().split())) for i in range(n)])

# first applying sum() function on array along axis 0
# then finding product of the result
# lastly printing the result
print(np.prod(np.sum(arr, axis = 0)))

2 2
1 2
3 4
24
